exp_name: huayandan3
model_state_dict_dir: ./wandb
run_ids:
# no dist
#  - 1w4mk6mr
#  - 3pdl0yv9
#  - e48u3t8g
#  - 14ooykvx
#  - 3tasch7j
# + dist emb
# - 3n8881jr
# - 24fad8c7
# - 2bd0ipht
 - 1o3wgoki

last_k_model: 1

data_home: ../data4bert
test_data: "huayandan_test_0620.json"
rel2id: rel2id.json
 
device_num: 1

encoder: BERT
bert_path: ../pretrained_models/BERT_EMR

# # for BiLSTM
# enc_hidden_size: 128
# dec_hidden_size: 256
# emb_dropout: 0.1
# rnn_dropout: 0.1
# word_embedding_dim: 100
# token2idx: token2idx.json
# pretrained_word_embedding_path: ../pretrained_word_emb/glove_100_webnlg.emb

batch_size: 16
force_split: false
max_test_seq_len: 128
sliding_len: 20
shaking_type: cln
dist_emb_size: 512
tok_pair_sample_rate: 1
correct: whole_text

# results
save_res: true
save_res_dir: ../results
# score: set true only when test set tagged
score: false